### PR TITLE
Environment Variables

### PR DESCRIPTION
**Pull request by ajpc500**
BOF to print environment variables for the current process

### CODE REVIEW

**Comment by kev169** [comment]
Hey, so just a heads up. This probably won't be merged in until the new year, but I skimmed through the code and it should be fine. I'm unsure if the test target works as is, so might want to change that. An example of the testing main is here : https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/master/src/SA/whoami/entry.c#L308 and for these 
```
DECLSPEC_IMPORT LPTCH WINAPI KERNEL32$GetEnvironmentStrings();
DECLSPEC_IMPORT WINBASEAPI BOOL WINAPI KERNEL32$FreeEnvironmentStringsA(LPSTR);
DECLSPEC_IMPORT WINBASEAPI int WINAPI KERNEL32$lstrlenA(LPCSTR);
```
you can add them to the bottom for the testing cases by doing something like this for the 3 of them
```
#define KERNEL32$GetEnvironmentStrings GetEnvironmentStrings
```
but that's the only things I noticed, thanks for the pull request though, hopefully can get it merged in soon.

**Comment by ajpc500** [comment]
Hey, no worries at all! Sorry yes, I missed the updates to the makefiles - updated accordingly 👍🏻

**Review by freefirex — APPROVED** [review]
Looks good to me!  Thank you for waiting and for the submission 💯

**Comment by ajpc500** [comment]
great, cheers both! 😄

**Pull request merged**
